//! Textures: binary Netpbm images cooked to GPU-ready MTEX
//! ([`mantis_formats::texture`]) with a mip chain and block compression.
//!
//! # Sources
//!
//! `*.ppm` (P6, 8-bit RGB), `*.pgm` (P5, 8-bit gray), and `*.pam` (P7, `DEPTH` 1 to 4 with
//! the matching `TUPLTYPE`, `MAXVAL` 255), at phase 0; the format is in [`netpbm`]. Each
//! cooks to one texture named after the source with the image extension replaced by
//! `.tex` (`art/rock.ppm` → `art/rock.tex`), kind [`AssetKind::Texture`], in the
//! presentation bundle. Width and height are 1 to
//! [`MAX_SIZE`](mantis_formats::texture::MAX_SIZE).
//!
//! # Settings sidecar
//!
//! An optional `<image file>.texture.toml` next to the image (`art/rock.ppm.texture.toml`)
//! sets top-level keys, all optional:
//!
//! ```toml
//! encoding = "bc7"     # "bc1", "bc4", "bc5", "bc7", or "rgba8"
//! srgb = true          # color data in sRGB (bc1, bc7, rgba8 only)
//! normal_map = false   # tangent-space normal map: bc5, R and G hold X and Y
//! mips = true          # full mip chain (false: level 0 only)
//! alpha_cutoff = 0.5   # bc1 only: texels with alpha below this (0 to 1) become transparent
//! ```
//!
//! Defaults: RGB images bc1, RGBA and gray-with-alpha images bc7, gray images bc4;
//! `normal_map = true` implies bc5. `srgb` defaults to true for bc1, bc7, and rgba8 and
//! false otherwise (and for normal maps). The format's rules are enforced at the sidecar
//! line: `srgb = true` only with bc1, bc7, or rgba8; a normal map only as bc5, never sRGB,
//! and only from an RGB or RGBA image; `alpha_cutoff` only with bc1, in 0 to 1 (rounded to
//! 8 bits). Block-compressed encodings need a width and height that are multiples of 4
//! (the GPU rule for sampling them); other sizes must use `rgba8`. Without a cutoff, bc1
//! ignores alpha. Unknown keys, tables, and values of the
//! wrong type are errors at their line. The sidecar is an input of this importer, never
//! cooked on its own.
//!
//! # Cooking
//!
//! Mips are generated by [`mips`] (2x2 box filter, linear light for sRGB, renormalized
//! normals) and each level is encoded by [`encode`] with the encoders [`bc1`], [`bc4`],
//! [`bc5`], and [`bc7`]. Each encoding records its encoder's `ENCODER_VERSION` in the
//! texture (0 for RGBA8), and [`IMPORTER_VERSION`] grows with every encoder version, so a
//! changed encoder changes both the bytes and the importer version. The cooked texture is
//! parsed back with the runtime parser before it is returned.

use std::sync::Arc;

use mantis_formats::bundle::{AssetKind, Domain};
use mantis_formats::texture::{Encoding, FLAG_NORMAL_MAP, FLAG_SRGB, TextureAsset, full_chain};

use crate::importer::{CookError, Cooked, ImportContext, Importer, Source};

pub mod bc1;
pub mod bc4;
pub mod bc5;
pub mod bc7;
pub mod encode;
mod fit;
pub mod mips;
pub mod netpbm;
pub mod settings;

/// This importer's own output version, before the encoders' versions are added.
const PIPELINE_VERSION: u32 = 1;

/// The importer version: its own version plus every encoder version, so a bump of any
/// encoder (versions only grow) bumps the importer too. BC5 shares BC4's version, which
/// is counted once.
pub const IMPORTER_VERSION: u32 =
    PIPELINE_VERSION + bc1::ENCODER_VERSION + bc4::ENCODER_VERSION + bc7::ENCODER_VERSION;

/// The sidecar suffix appended to an image path.
pub const SIDECAR_SUFFIX: &str = ".texture.toml";

/// The Netpbm texture importer.
#[derive(Clone, Copy, Debug, Default)]
pub struct Netpbm;

fn format_of(path: &str) -> Option<netpbm::Format> {
    let ext = std::path::Path::new(path).extension()?.to_str()?;
    if ext.eq_ignore_ascii_case("ppm") {
        Some(netpbm::Format::Ppm)
    } else if ext.eq_ignore_ascii_case("pgm") {
        Some(netpbm::Format::Pgm)
    } else if ext.eq_ignore_ascii_case("pam") {
        Some(netpbm::Format::Pam)
    } else {
        None
    }
}

impl Importer for Netpbm {
    fn name(&self) -> &'static str {
        "texture.netpbm"
    }

    fn version(&self) -> u32 {
        IMPORTER_VERSION
    }

    fn phase(&self) -> u32 {
        0
    }

    fn accepts(&self, path: &str) -> bool {
        format_of(path).is_some()
    }

    fn inputs(&self, path: &str) -> bool {
        path.strip_suffix(SIDECAR_SUFFIX)
            .is_some_and(|image| format_of(image).is_some())
    }

    fn import(&self, source: &Source<'_>, ctx: &ImportContext<'_>) -> Result<Vec<Cooked>, CookError> {
        let format = format_of(source.path)
            .ok_or_else(|| CookError::at(source.path, 0, "not a .ppm, .pgm, or .pam image"))?;
        let image = netpbm::parse(source.bytes, format)
            .map_err(|e| CookError::at(source.path, e.line, &e.message))?;
        let sidecar_path = format!("{}{SIDECAR_SUFFIX}", source.path);
        let sidecar = ctx.source(&sidecar_path);
        let settings = settings::resolve(sidecar.as_ref(), image.channels)?;
        // GPUs sample block-compressed textures only when the base level is whole blocks.
        if settings.encoding != Encoding::Rgba8
            && (!image.width.is_multiple_of(4) || !image.height.is_multiple_of(4))
        {
            return Err(CookError::at(
                source.path,
                0,
                &format!(
                    "{}x{} is not a multiple of 4 in both dimensions, which block compression needs; resize the image or set `encoding = \"rgba8\"` in `{sidecar_path}`",
                    image.width, image.height
                ),
            ));
        }
        let bytes = cook(&image, &settings);
        TextureAsset::parse(&bytes)
            .map_err(|e| CookError::at(source.path, 0, &format!("the cooked texture does not load: {e}")))?;
        Ok(vec![Cooked {
            name: format!("{}.tex", source.stem_path()),
            kind: AssetKind::Texture,
            domain: Domain::Presentation,
            bytes,
        }])
    }
}

/// Cooks a decoded image with resolved settings to MTEX bytes.
pub fn cook(image: &netpbm::Image, settings: &settings::Settings) -> Vec<u8> {
    let space = if settings.normal_map {
        mips::Space::Normal
    } else if settings.srgb {
        mips::Space::Srgb
    } else {
        mips::Space::Linear
    };
    let levels = if settings.mips {
        full_chain(image.width, image.height)
    } else {
        1
    };
    let chain = mips::chain(image.width, image.height, &image.texels, space, levels);
    let mut data = Vec::with_capacity(chain.len());
    for (level, texels) in (0u32..).zip(&chain) {
        let (w, h) = mantis_formats::texture::mip_size(image.width, image.height, level);
        data.push(encode::encode_image(
            settings.encoding,
            w,
            h,
            texels,
            settings.alpha_cutoff,
        ));
    }
    let mut flags = 0;
    if settings.srgb {
        flags |= FLAG_SRGB;
    }
    if settings.normal_map {
        flags |= FLAG_NORMAL_MAP;
    }
    TextureAsset {
        encoding: settings.encoding,
        flags,
        encoder_version: encode::encoder_version(settings.encoding),
        width: image.width,
        height: image.height,
        mips: data,
    }
    .encode()
}

/// This module's importers.
pub fn importers() -> Vec<Arc<dyn Importer>> {
    vec![Arc::new(Netpbm)]
}
