//! The modules linked into this package's server. Generated by
//! `mantis-modsync` for package `toy`; do not edit. Regenerate with
//! `cargo run -p mantis-modsync -- <workspace root> <package>`.

use std::sync::Arc;

use mantis_server::modules::ServerModule;

/// Every linked module's server half, in crate-name order.
#[must_use]
#[rustfmt::skip]
pub fn linked() -> Vec<Arc<dyn ServerModule>> {
    vec![
        Arc::new(std_auction_server::Module),
        Arc::new(std_chat_server::Module),
        Arc::new(std_containers_server::Module),
        Arc::new(std_friends_server::Module),
        Arc::new(std_guild_server::Module),
        Arc::new(std_mail_server::Module),
        Arc::new(std_party_server::Module),
        Arc::new(std_titles_server::Module),
        Arc::new(std_vendor_server::Module),
    ]
}

/// Every module manifest the package resolves at start-up, as
/// `(origin package, manifest text)`.
#[rustfmt::skip]
pub const MANIFESTS: &[(&str, &str)] = &[
    ("std", include_str!("../../../std/modules/auction/manifest.toml")),
    ("std", include_str!("../../../std/modules/chat/manifest.toml")),
    ("std", include_str!("../../../std/modules/containers/manifest.toml")),
    ("std", include_str!("../../../std/modules/friends/manifest.toml")),
    ("std", include_str!("../../../std/modules/guild/manifest.toml")),
    ("std", include_str!("../../../std/modules/mail/manifest.toml")),
    ("std", include_str!("../../../std/modules/party/manifest.toml")),
    ("std", include_str!("../../../std/modules/titles/manifest.toml")),
    ("std", include_str!("../../../std/modules/vendor/manifest.toml")),
];
