//! The wire runtime: the "idl codecs" of plan section 5.
//!
//! Code generated by `mantis-idl` and the unified log both encode through this
//! module. Everything here validates at the boundary and fails closed
//! (principles 2 and 6):
//!
//! - integers are fixed-width little-endian;
//! - `f32` must be finite, and NaN or infinity is refused on decode;
//! - `bool` is one byte, exactly 0 or 1;
//! - lists, strings, and byte strings carry a `u16` length that must not exceed
//!   the declared bound, and are stored inline in [`BoundedArray`], so decoding
//!   never allocates and a hostile length can never trigger a large allocation;
//! - strings must be valid UTF-8;
//! - enums and bit sets refuse undefined values;
//! - [`decode_exact`] refuses trailing bytes.
//!
//! [`FuzzSample`] produces structurally valid random values for the
//! structure-aware fuzzer in `mantis-testkit`.

mod bounded;

pub use bounded::{BoundedArray, WireString};

use core::fmt;

use crate::content::ContentHash;
use crate::ecs::EntityId;
use crate::kinematics::{AimAngles, Angle16, InputSeq, MoveButtons, MoveInput};
use crate::math::Vec3;
use crate::rng::Rng;
use crate::time::Tick;

/// A payload did not decode.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum DecodeError {
    /// The bytes ended early.
    UnexpectedEnd,
    /// Bytes remained after the value.
    TrailingBytes,
    /// A field held a value outside its domain (named).
    Invalid(&'static str),
}

impl fmt::Display for DecodeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnexpectedEnd => f.write_str("unexpected end of input"),
            Self::TrailingBytes => f.write_str("trailing bytes"),
            Self::Invalid(what) => write!(f, "invalid {what}"),
        }
    }
}

impl std::error::Error for DecodeError {}

/// Appends little-endian values to a byte vector. Allocation-free while the
/// vector has spare capacity.
pub struct Encoder<'a> {
    out: &'a mut Vec<u8>,
}

impl<'a> Encoder<'a> {
    /// An encoder appending to `out`.
    pub fn new(out: &'a mut Vec<u8>) -> Self {
        Self { out }
    }

    /// Appends raw bytes.
    pub fn bytes(&mut self, b: &[u8]) {
        self.out.extend_from_slice(b);
    }

    /// Appends a `u8`.
    pub fn u8(&mut self, v: u8) {
        self.out.push(v);
    }

    /// Appends a `u16`.
    pub fn u16(&mut self, v: u16) {
        self.bytes(&v.to_le_bytes());
    }

    /// Appends a `u32`.
    pub fn u32(&mut self, v: u32) {
        self.bytes(&v.to_le_bytes());
    }

    /// Appends a `u64`.
    pub fn u64(&mut self, v: u64) {
        self.bytes(&v.to_le_bytes());
    }

    /// Appends an `i8`.
    pub fn i8(&mut self, v: i8) {
        self.bytes(&v.to_le_bytes());
    }

    /// Appends an `i16`.
    pub fn i16(&mut self, v: i16) {
        self.bytes(&v.to_le_bytes());
    }

    /// Appends an `i32`.
    pub fn i32(&mut self, v: i32) {
        self.bytes(&v.to_le_bytes());
    }

    /// Appends an `i64`.
    pub fn i64(&mut self, v: i64) {
        self.bytes(&v.to_le_bytes());
    }

    /// Appends an `f32` by its bits.
    pub fn f32(&mut self, v: f32) {
        self.u32(v.to_bits());
    }

    /// Appends a `bool` as 0 or 1.
    pub fn bool(&mut self, v: bool) {
        self.u8(u8::from(v));
    }

    /// Bytes written so far by everyone using the underlying vector.
    #[must_use]
    pub fn len(&self) -> usize {
        self.out.len()
    }

    /// True when the underlying vector is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.out.is_empty()
    }
}

/// Reads little-endian values from a byte slice, failing closed.
pub struct Decoder<'a> {
    bytes: &'a [u8],
}

impl<'a> Decoder<'a> {
    /// A decoder over `bytes`.
    #[must_use]
    pub fn new(bytes: &'a [u8]) -> Self {
        Self { bytes }
    }

    /// Takes `N` bytes.
    ///
    /// # Errors
    /// [`DecodeError::UnexpectedEnd`].
    pub fn array<const N: usize>(&mut self) -> Result<[u8; N], DecodeError> {
        let (head, rest) = self
            .bytes
            .split_first_chunk::<N>()
            .ok_or(DecodeError::UnexpectedEnd)?;
        self.bytes = rest;
        Ok(*head)
    }

    /// Takes `n` bytes without copying.
    ///
    /// # Errors
    /// [`DecodeError::UnexpectedEnd`].
    pub fn take(&mut self, n: usize) -> Result<&'a [u8], DecodeError> {
        if n > self.bytes.len() {
            return Err(DecodeError::UnexpectedEnd);
        }
        let (head, rest) = self.bytes.split_at(n);
        self.bytes = rest;
        Ok(head)
    }

    /// Reads a `u8`.
    ///
    /// # Errors
    /// [`DecodeError::UnexpectedEnd`].
    pub fn u8(&mut self) -> Result<u8, DecodeError> {
        Ok(u8::from_le_bytes(self.array()?))
    }

    /// Reads a `u16`.
    ///
    /// # Errors
    /// [`DecodeError::UnexpectedEnd`].
    pub fn u16(&mut self) -> Result<u16, DecodeError> {
        Ok(u16::from_le_bytes(self.array()?))
    }

    /// Reads a `u32`.
    ///
    /// # Errors
    /// [`DecodeError::UnexpectedEnd`].
    pub fn u32(&mut self) -> Result<u32, DecodeError> {
        Ok(u32::from_le_bytes(self.array()?))
    }

    /// Reads a `u64`.
    ///
    /// # Errors
    /// [`DecodeError::UnexpectedEnd`].
    pub fn u64(&mut self) -> Result<u64, DecodeError> {
        Ok(u64::from_le_bytes(self.array()?))
    }

    /// Reads an `i8`.
    ///
    /// # Errors
    /// [`DecodeError::UnexpectedEnd`].
    pub fn i8(&mut self) -> Result<i8, DecodeError> {
        Ok(i8::from_le_bytes(self.array()?))
    }

    /// Reads an `i16`.
    ///
    /// # Errors
    /// [`DecodeError::UnexpectedEnd`].
    pub fn i16(&mut self) -> Result<i16, DecodeError> {
        Ok(i16::from_le_bytes(self.array()?))
    }

    /// Reads an `i32`.
    ///
    /// # Errors
    /// [`DecodeError::UnexpectedEnd`].
    pub fn i32(&mut self) -> Result<i32, DecodeError> {
        Ok(i32::from_le_bytes(self.array()?))
    }

    /// Reads an `i64`.
    ///
    /// # Errors
    /// [`DecodeError::UnexpectedEnd`].
    pub fn i64(&mut self) -> Result<i64, DecodeError> {
        Ok(i64::from_le_bytes(self.array()?))
    }

    /// Reads a finite `f32` (non-finite values are refused at the boundary).
    ///
    /// # Errors
    /// [`DecodeError::UnexpectedEnd`], or [`DecodeError::Invalid`] for NaN
    /// or infinity.
    pub fn finite_f32(&mut self) -> Result<f32, DecodeError> {
        let v = f32::from_bits(self.u32()?);
        if v.is_finite() {
            Ok(v)
        } else {
            Err(DecodeError::Invalid("non-finite float"))
        }
    }

    /// Reads a `bool` (exactly 0 or 1).
    ///
    /// # Errors
    /// [`DecodeError::UnexpectedEnd`], or [`DecodeError::Invalid`] for any
    /// other byte.
    pub fn bool(&mut self) -> Result<bool, DecodeError> {
        match self.u8()? {
            0 => Ok(false),
            1 => Ok(true),
            _ => Err(DecodeError::Invalid("bool")),
        }
    }

    /// Reads a `u16` length and checks it against `max`.
    ///
    /// # Errors
    /// [`DecodeError::UnexpectedEnd`], or [`DecodeError::Invalid`] when the
    /// length exceeds `max`.
    pub fn len(&mut self, max: usize) -> Result<usize, DecodeError> {
        let n = usize::from(self.u16()?);
        if n > max {
            Err(DecodeError::Invalid("length over bound"))
        } else {
            Ok(n)
        }
    }

    /// Bytes not yet read.
    #[must_use]
    pub fn remaining(&self) -> usize {
        self.bytes.len()
    }

    /// Succeeds only if every byte was consumed.
    ///
    /// # Errors
    /// [`DecodeError::TrailingBytes`].
    pub fn finish(&self) -> Result<(), DecodeError> {
        if self.bytes.is_empty() {
            Ok(())
        } else {
            Err(DecodeError::TrailingBytes)
        }
    }
}

/// A value with a stable binary encoding.
pub trait Wire: Sized {
    /// Appends the encoding.
    fn encode(&self, e: &mut Encoder<'_>);

    /// Reads one value, validating every field.
    ///
    /// # Errors
    /// Any [`DecodeError`].
    fn decode(d: &mut Decoder<'_>) -> Result<Self, DecodeError>;
}

/// Decodes exactly one `T` from `bytes`, refusing trailing bytes.
///
/// # Errors
/// Any [`DecodeError`].
pub fn decode_exact<T: Wire>(bytes: &[u8]) -> Result<T, DecodeError> {
    let mut d = Decoder::new(bytes);
    let v = T::decode(&mut d)?;
    d.finish()?;
    Ok(v)
}

/// Appends the encoding of `value` to `out`.
pub fn encode_into<T: Wire>(value: &T, out: &mut Vec<u8>) {
    value.encode(&mut Encoder::new(out));
}

/// Decodes exactly one message `M`, naming it in the error.
///
/// # Errors
/// [`WireError::Decode`] when the payload does not decode exactly.
pub fn decode_message<M: Message>(bytes: &[u8]) -> Result<M, WireError> {
    decode_exact::<M>(bytes).map_err(|error| WireError::Decode {
        message: M::NAME,
        error,
    })
}

/// Id of a message within its schema's append-only registry.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct MessageId(pub u16);

/// A top-level message with a registered id.
pub trait Message: Wire {
    /// The registered id.
    const ID: MessageId;
    /// The schema name.
    const NAME: &'static str;
}

/// A hand-written validator refused a decoded message.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct ValidationError(pub &'static str);

impl fmt::Display for ValidationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "validation failed: {}", self.0)
    }
}

impl std::error::Error for ValidationError {}

/// An inbound frame was refused.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum WireError {
    /// No message has this id.
    UnknownMessage(MessageId),
    /// The payload did not decode.
    Decode {
        /// The message.
        message: &'static str,
        /// Why.
        error: DecodeError,
    },
    /// The payload decoded but its validator refused it.
    Rejected {
        /// The message.
        message: &'static str,
        /// Why.
        reason: ValidationError,
    },
}

impl fmt::Display for WireError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnknownMessage(id) => write!(f, "unknown message id {}", id.0),
            Self::Decode { message, error } => write!(f, "{message}: {error}"),
            Self::Rejected { message, reason } => write!(f, "{message}: {reason}"),
        }
    }
}

impl std::error::Error for WireError {}

/// Produces structurally valid random values for the structure-aware fuzzer.
pub trait FuzzSample: Sized {
    /// A random valid value.
    fn fuzz_sample(rng: &mut Rng) -> Self;
}

macro_rules! int_wire {
    ($($t:ident),*) => {$(
        impl Wire for $t {
            fn encode(&self, e: &mut Encoder<'_>) {
                e.$t(*self);
            }
            fn decode(d: &mut Decoder<'_>) -> Result<Self, DecodeError> {
                d.$t()
            }
        }
        impl FuzzSample for $t {
            #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap, clippy::cast_lossless)] // taking low bits
            fn fuzz_sample(rng: &mut Rng) -> Self {
                // Bias toward edges: 0, 1, MAX, MIN, and small values.
                match rng.below(8) {
                    0 => 0 as $t,
                    1 => 1 as $t,
                    2 => $t::MAX,
                    3 => $t::MIN,
                    4 => rng.below(16) as $t,
                    _ => rng.next_u64() as $t,
                }
            }
        }
    )*};
}
int_wire!(u8, u16, u32, u64, i8, i16, i32, i64);

impl Wire for bool {
    fn encode(&self, e: &mut Encoder<'_>) {
        e.bool(*self);
    }
    fn decode(d: &mut Decoder<'_>) -> Result<Self, DecodeError> {
        d.bool()
    }
}

impl FuzzSample for bool {
    fn fuzz_sample(rng: &mut Rng) -> Self {
        rng.chance(1, 2)
    }
}

/// Finite only.
impl Wire for f32 {
    fn encode(&self, e: &mut Encoder<'_>) {
        e.f32(*self);
    }
    fn decode(d: &mut Decoder<'_>) -> Result<Self, DecodeError> {
        d.finite_f32()
    }
}

impl FuzzSample for f32 {
    fn fuzz_sample(rng: &mut Rng) -> Self {
        const EDGES: [f32; 8] = [
            0.0,
            -0.0,
            1.0,
            -1.0,
            f32::MIN_POSITIVE,
            f32::MAX,
            f32::MIN,
            1.0e-40,
        ];
        if rng.chance(1, 4) {
            return EDGES.get(rng.below(8) as usize).copied().unwrap_or(0.0);
        }
        loop {
            let v = f32::from_bits(rng.next_u32());
            if v.is_finite() {
                return v;
            }
        }
    }
}

/// A one-byte tag (0 absent, 1 present), then the value.
impl<T: Wire> Wire for Option<T> {
    fn encode(&self, e: &mut Encoder<'_>) {
        match self {
            None => e.u8(0),
            Some(v) => {
                e.u8(1);
                v.encode(e);
            }
        }
    }
    fn decode(d: &mut Decoder<'_>) -> Result<Self, DecodeError> {
        match d.u8()? {
            0 => Ok(None),
            1 => Ok(Some(T::decode(d)?)),
            _ => Err(DecodeError::Invalid("option tag")),
        }
    }
}

impl<T: FuzzSample> FuzzSample for Option<T> {
    fn fuzz_sample(rng: &mut Rng) -> Self {
        rng.chance(1, 2).then(|| T::fuzz_sample(rng))
    }
}

impl Wire for EntityId {
    fn encode(&self, e: &mut Encoder<'_>) {
        e.u64(self.to_bits());
    }
    fn decode(d: &mut Decoder<'_>) -> Result<Self, DecodeError> {
        Ok(Self::from_bits(d.u64()?))
    }
}

impl FuzzSample for EntityId {
    fn fuzz_sample(rng: &mut Rng) -> Self {
        Self::new(u32::fuzz_sample(rng), u32::fuzz_sample(rng))
    }
}

impl Wire for Tick {
    fn encode(&self, e: &mut Encoder<'_>) {
        e.u64(self.0);
    }
    fn decode(d: &mut Decoder<'_>) -> Result<Self, DecodeError> {
        Ok(Self(d.u64()?))
    }
}

impl FuzzSample for Tick {
    fn fuzz_sample(rng: &mut Rng) -> Self {
        Self(u64::fuzz_sample(rng))
    }
}

/// Three finite `f32`.
impl Wire for Vec3 {
    fn encode(&self, e: &mut Encoder<'_>) {
        e.f32(self.x);
        e.f32(self.y);
        e.f32(self.z);
    }
    fn decode(d: &mut Decoder<'_>) -> Result<Self, DecodeError> {
        Ok(Self::new(d.finite_f32()?, d.finite_f32()?, d.finite_f32()?))
    }
}

impl FuzzSample for Vec3 {
    fn fuzz_sample(rng: &mut Rng) -> Self {
        Self::new(
            f32::fuzz_sample(rng),
            f32::fuzz_sample(rng),
            f32::fuzz_sample(rng),
        )
    }
}

impl Wire for Angle16 {
    fn encode(&self, e: &mut Encoder<'_>) {
        e.u16(self.0);
    }
    fn decode(d: &mut Decoder<'_>) -> Result<Self, DecodeError> {
        Ok(Self(d.u16()?))
    }
}

impl FuzzSample for Angle16 {
    fn fuzz_sample(rng: &mut Rng) -> Self {
        Self(u16::fuzz_sample(rng))
    }
}

impl Wire for InputSeq {
    fn encode(&self, e: &mut Encoder<'_>) {
        e.u32(self.0);
    }
    fn decode(d: &mut Decoder<'_>) -> Result<Self, DecodeError> {
        Ok(Self(d.u32()?))
    }
}

impl FuzzSample for InputSeq {
    fn fuzz_sample(rng: &mut Rng) -> Self {
        Self(u32::fuzz_sample(rng))
    }
}

/// Undefined bits are refused.
impl Wire for MoveButtons {
    fn encode(&self, e: &mut Encoder<'_>) {
        e.u16(self.bits());
    }
    fn decode(d: &mut Decoder<'_>) -> Result<Self, DecodeError> {
        Self::from_bits(d.u16()?).ok_or(DecodeError::Invalid("move buttons"))
    }
}

impl FuzzSample for MoveButtons {
    #[allow(clippy::cast_possible_truncation)] // below(64) fits u16
    fn fuzz_sample(rng: &mut Rng) -> Self {
        Self::from_bits(rng.below(u32::from(Self::ALL.bits()) + 1) as u16).unwrap_or(Self::NONE)
    }
}

/// `seq u32, tick u64, buttons u16, yaw u16, aim yaw u16, aim pitch u16`
/// (20 bytes).
impl Wire for MoveInput {
    fn encode(&self, e: &mut Encoder<'_>) {
        self.seq.encode(e);
        self.tick.encode(e);
        self.buttons.encode(e);
        self.yaw.encode(e);
        self.aim.yaw.encode(e);
        self.aim.pitch.encode(e);
    }
    fn decode(d: &mut Decoder<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            seq: InputSeq::decode(d)?,
            tick: Tick::decode(d)?,
            buttons: MoveButtons::decode(d)?,
            yaw: Angle16::decode(d)?,
            aim: AimAngles {
                yaw: Angle16::decode(d)?,
                pitch: Angle16::decode(d)?,
            },
        })
    }
}

impl FuzzSample for MoveInput {
    fn fuzz_sample(rng: &mut Rng) -> Self {
        Self {
            seq: InputSeq::fuzz_sample(rng),
            tick: Tick::fuzz_sample(rng),
            buttons: MoveButtons::fuzz_sample(rng),
            yaw: Angle16::fuzz_sample(rng),
            aim: AimAngles {
                yaw: Angle16::fuzz_sample(rng),
                pitch: Angle16::fuzz_sample(rng),
            },
        }
    }
}

impl Wire for ContentHash {
    fn encode(&self, e: &mut Encoder<'_>) {
        e.bytes(self.as_bytes());
    }
    fn decode(d: &mut Decoder<'_>) -> Result<Self, DecodeError> {
        Ok(Self::from_bytes(d.array()?))
    }
}

impl FuzzSample for ContentHash {
    fn fuzz_sample(rng: &mut Rng) -> Self {
        let mut b = [0u8; 32];
        for chunk in b.chunks_mut(8) {
            for (dst, src) in chunk.iter_mut().zip(rng.next_u64().to_le_bytes()) {
                *dst = src;
            }
        }
        Self::from_bytes(b)
    }
}

#[cfg(test)]
mod tests;
