//! WGSL generation for one material.

use core::fmt::Write;

use mantis_formats::material::{LightingModel, MaterialAsset, Node, NodeId, PermutationKey, ValueType};

use crate::layout;

/// Formats an `f32` as a WGSL float literal (always with a decimal point or exponent).
fn float(v: f32) -> String {
    let s = format!("{v:?}");
    if s.contains('.') || s.contains('e') || s.contains("inf") || s.contains("NaN") {
        s
    } else {
        format!("{s}.0")
    }
}

fn vec3(v: [f32; 3]) -> String {
    let [x, y, z] = v;
    format!("vec3<f32>({}, {}, {})", float(x), float(y), float(z))
}

/// Feature constants every module starts with.
pub(crate) fn constants(out: &mut String, asset: &MaterialAsset, key: PermutationKey) {
    let g = &asset.graph.graph;
    let cutoff = g.outputs.alpha_cutoff.unwrap_or(0.0);
    let (width, color) = g.outline.map_or((0.0, [0.0; 3]), |o| (o.width_px, o.color));
    let unlit = matches!(g.lighting, LightingModel::Unlit);
    let _ = writeln!(
        out,
        "// Generated by mantis-shadergen. Permutation {:#06x}.",
        key.bits()
    );
    if key.bindless() {
        // Enable directives precede every other item.
        out.push_str(
            "enable wgpu_binding_array;
",
        );
    }
    let _ = writeln!(out, "const ALPHA_TEST: bool = {};", key.alpha_test());
    let _ = writeln!(out, "const ALPHA_CUTOFF: f32 = {};", float(cutoff));
    let _ = writeln!(out, "const LIGHTMAPPED: bool = {};", key.lightmapped());
    let _ = writeln!(out, "const MATERIAL_UNLIT: bool = {unlit};");
    let _ = writeln!(out, "const OUTLINE_WIDTH_PX: f32 = {};", float(width));
    let _ = writeln!(out, "const OUTLINE_COLOR: vec3<f32> = {};", vec3(color));
}

/// Material texture declarations.
pub(crate) fn textures(out: &mut String, bindless: bool) {
    let first = layout::MATERIAL_TEXTURE_BINDING;
    let group = layout::GROUP_MATERIAL;
    if bindless {
        let _ = writeln!(
            out,
            "@group({}) @binding(0) var material_textures: binding_array<texture_2d<f32>, {}>;",
            layout::GROUP_TEXTURES,
            layout::BINDLESS_TEXTURES
        );
    } else {
        for slot in 0..4u32 {
            let _ = writeln!(
                out,
                "@group({group}) @binding({}) var material_texture_{slot}: texture_2d<f32>;",
                first + slot
            );
        }
    }
}

/// The texture object expression for `slot`.
fn texture(slot: u8, bindless: bool) -> String {
    if bindless {
        format!("material_textures[material.texture_index[{slot}]]")
    } else {
        format!("material_texture_{slot}")
    }
}

fn splat(ty: ValueType, scalar: &str) -> String {
    match ty {
        ValueType::F32 => scalar.to_owned(),
        other => format!("{}({scalar})", other.wgsl()),
    }
}

fn node_expr(node: &Node, types: &[ValueType], bindless: bool) -> String {
    let n = |id: NodeId| format!("n{}", id.0);
    let ty = |id: NodeId| types.get(usize::from(id.0)).copied().unwrap_or(ValueType::F32);
    match *node {
        Node::Uv0 => "mi.uv0".to_owned(),
        Node::Uv1 => "mi.uv1".to_owned(),
        Node::WorldPosition => "mi.world_position".to_owned(),
        Node::WorldNormal => "mi.world_normal".to_owned(),
        Node::ViewDirection => "mi.view_direction".to_owned(),
        Node::Time => "mi.time".to_owned(),
        Node::Constant(v, t) => {
            let parts: Vec<String> = v
                .iter()
                .take(usize::from(t.components()))
                .map(|c| float(*c))
                .collect();
            if t == ValueType::F32 {
                parts.join("")
            } else {
                format!("{}({})", t.wgsl(), parts.join(", "))
            }
        }
        Node::ScalarParam(i) => {
            let lane = ["x", "y", "z", "w"]
                .get(usize::from(i % 4))
                .copied()
                .unwrap_or("x");
            format!("material.scalars[{}].{lane}", i / 4)
        }
        Node::ColorParam(i) => format!("material.colors[{i}]"),
        Node::Texture { slot, uv } => format!(
            "textureSample({}, material_sampler, {})",
            texture(slot, bindless),
            n(uv)
        ),
        Node::Add(a, b) => format!("({} + {})", n(a), n(b)),
        Node::Subtract(a, b) => format!("({} - {})", n(a), n(b)),
        Node::Multiply(a, b) => format!("({} * {})", n(a), n(b)),
        Node::Divide(a, b) => format!("({} / {})", n(a), n(b)),
        Node::Lerp(a, b, t) => format!("mix({}, {}, {})", n(a), n(b), n(t)),
        Node::Dot(a, b) => format!("dot({}, {})", n(a), n(b)),
        Node::Normalize(a) => format!("normalize({})", n(a)),
        Node::Saturate(a) => format!("saturate({})", n(a)),
        Node::OneMinus(a) => format!("(1.0 - {})", n(a)),
        Node::Power(a, e) => {
            let t = ty(a);
            format!("pow(max({}, {}), {})", n(a), splat(t, "0.0"), splat(t, &n(e)))
        }
        Node::Swizzle(a, idx, len) => {
            if ty(a) == ValueType::F32 {
                let t = ValueType::with_components(len).unwrap_or(ValueType::F32);
                splat(t, &n(a))
            } else {
                let letters: String = idx
                    .iter()
                    .take(usize::from(len))
                    .filter_map(|c| ["x", "y", "z", "w"].get(usize::from(*c)).copied())
                    .collect();
                format!("{}.{letters}", n(a))
            }
        }
        Node::Combine(parts) => {
            let inner: Vec<String> = parts.iter().flatten().map(|p| n(*p)).collect();
            let t =
                ValueType::with_components(u8::try_from(inner.len()).unwrap_or(4)).unwrap_or(ValueType::Vec4);
            format!("{}({})", t.wgsl(), inner.join(", "))
        }
        Node::Fresnel(p) => format!(
            "pow(1.0 - saturate(dot(mi.world_normal, mi.view_direction)), {})",
            n(p)
        ),
    }
}

/// `material_surface`, `material_diffuse`, and `material_rim`.
pub(crate) fn material_functions(out: &mut String, asset: &MaterialAsset, bindless: bool) {
    let typed = &asset.graph;
    let g = &typed.graph;
    out.push_str("\nfn material_surface(mi: MaterialInput) -> SurfaceOutput {\n");
    for (i, node) in g.nodes.iter().enumerate() {
        let _ = writeln!(out, "    let n{i} = {};", node_expr(node, &typed.types, bindless));
    }
    let base_ty = typed.types.get(usize::from(g.outputs.base_color.0)).copied();
    let base = if base_ty == Some(ValueType::Vec4) {
        format!("n{}.xyz", g.outputs.base_color.0)
    } else {
        format!("n{}", g.outputs.base_color.0)
    };
    out.push_str("    var out: SurfaceOutput;\n");
    let _ = writeln!(out, "    out.base_color = {base};");
    let _ = writeln!(
        out,
        "    out.alpha = {};",
        g.outputs.alpha.map_or("1.0".to_owned(), |a| format!("n{}", a.0))
    );
    let _ = writeln!(
        out,
        "    out.emissive = {};",
        g.outputs
            .emissive
            .map_or("vec3<f32>(0.0)".to_owned(), |e| format!("n{}", e.0))
    );
    out.push_str("    return out;\n}\n");

    // Direct-light response. `lit` is n . l times the shadow factor, in [-1, 1].
    out.push_str("\nfn material_diffuse(lit: f32, light: vec3<f32>) -> vec3<f32> {\n");
    match g.lighting {
        LightingModel::Unlit => out.push_str("    return vec3<f32>(0.0);\n"),
        LightingModel::Lambert => out.push_str("    return max(lit, 0.0) * light;\n"),
        LightingModel::Toon {
            bands,
            softness,
            shadow_tint,
        } => {
            let half = float((softness * 0.5).max(0.0001));
            let _ = writeln!(out, "    let bands = {};", float(f32::from(bands)));
            out.push_str("    let scaled = saturate(lit) * bands;\n");
            out.push_str("    let band = floor(scaled);\n");
            let _ = writeln!(
                out,
                "    let edge = smoothstep(0.5 - {half}, 0.5 + {half}, fract(scaled));"
            );
            out.push_str("    let level = min((band + edge) / bands, 1.0);\n");
            let _ = writeln!(
                out,
                "    return mix({}, vec3<f32>(1.0), level) * light;",
                vec3(shadow_tint)
            );
        }
        LightingModel::ToonRamp { slot } => {
            let _ = writeln!(
                out,
                "    return textureSampleLevel({}, material_sampler, vec2<f32>(saturate(lit), 0.5), 0.0).rgb * light;",
                texture(slot, bindless)
            );
        }
    }
    out.push_str("}\n");

    out.push_str("\nfn material_rim(n: vec3<f32>, v: vec3<f32>) -> vec3<f32> {\n");
    match g.rim {
        Some(r) => {
            let _ = writeln!(
                out,
                "    return {} * {} * pow(1.0 - saturate(dot(n, v)), {});",
                vec3(r.color),
                float(r.intensity),
                float(r.power)
            );
        }
        None => out.push_str("    return vec3<f32>(0.0);\n"),
    }
    out.push_str("}\n\n");
}

#[cfg(test)]
mod tests {
    use super::float;

    #[test]
    fn float_literals_are_always_floats() {
        assert_eq!(float(1.0), "1.0");
        assert_eq!(float(0.25), "0.25");
        assert_eq!(float(-2.0), "-2.0");
        assert_eq!(float(1e-7), "1e-7");
        assert_eq!(float(1e20), "1e20");
    }
}
