//! The toy package manifest as the client reads it: the content hash it announces in
//! `Hello`, the tick rate, and the movement tunables prediction runs with.
//!
//! The client reads the same `package.toml` as the server, with the same small grammar
//! (`key = number   # unit` inside `[tunables.*]` tables; a unit comment is required), so
//! the client predicts with exactly the parameters the server simulates. Only the tables
//! the client needs are read; the others are skipped.

use mantis_core::content::ContentHash;
use mantis_core::kinematics::MotionParams;
use mantis_core::time::TickRate;

/// The manifest compiled into the client.
pub const PACKAGE_TOML: &str = include_str!("../../package.toml");

/// The uncooked manifest hash: the handshake content hash of a server running without
/// a cook (in-process tests). A cooked server checks the gameplay bundle hash instead
/// ([`crate::world::OpenedWorld::content_hash`]).
pub fn content() -> ContentHash {
    ContentHash::of(PACKAGE_TOML.as_bytes())
}

/// The package's resolved module graph: every module manifest linked into the client
/// (`modules::MANIFESTS`, generated by `mantis-modsync`) resolved against this package's
/// `uses`, `overrides`, and `[flags]`, exactly as the server resolves it.
///
/// # Errors
/// The manifest or resolution error, as text (the client refuses to start).
pub fn module_graph() -> Result<mantis_core::module::ModuleGraph, String> {
    use mantis_core::module::{Discovered, parse_manifest, parse_package, resolve};
    let package = parse_package(PACKAGE_TOML).map_err(|e| format!("package.toml: {e:?}"))?;
    let found = crate::modules::MANIFESTS
        .iter()
        .map(|(origin, text)| {
            Ok(Discovered {
                origin: (*origin).to_owned(),
                manifest: parse_manifest(text).map_err(|e| format!("{origin} manifest: {e:?}"))?,
            })
        })
        .collect::<Result<Vec<_>, String>>()?;
    resolve(&package, &found, &std::collections::BTreeMap::new()).map_err(|e| format!("modules: {e:?}"))
}

/// The client mod keys the package permits (`[package] client_mods`): a mod with another
/// key is refused before the handshake, with a notice.
///
/// # Errors
/// The manifest error, as text.
pub fn client_mods() -> Result<Vec<String>, String> {
    mantis_core::module::parse_package(PACKAGE_TOML)
        .map(|p| p.client_mods)
        .map_err(|e| format!("package.toml: {e:?}"))
}

/// The toy package's own mods (`packages/toy/mods`, as built), used by its end-to-end
/// tests and as the development default; a player's mods come from their own directory
/// (`toy-client --mods DIR`).
pub fn package_mods_dir() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("mods")
}

/// What the client tunes from the manifest.
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct Tunables {
    /// Simulation rate (the client ticks at the server's rate for Predictive movement).
    pub tick_rate: TickRate,
    /// Movement of the class.
    pub motion: MotionParams,
}

/// A manifest the client cannot use.
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum PackageError {
    /// A line inside a read table is not `key = value # unit`.
    Syntax(usize),
    /// A key no tunable has.
    Unknown(String),
    /// A key given twice.
    Duplicate(String),
    /// A required key is absent.
    Missing(&'static str),
    /// A line without a unit comment.
    MissingUnit(String),
    /// A value that is not a finite number of the right kind.
    BadValue(String),
}

impl core::fmt::Display for PackageError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Syntax(line) => write!(f, "line {line}: expected `key = value  # unit`"),
            Self::Unknown(k) => write!(f, "unknown tunable `{k}`"),
            Self::Duplicate(k) => write!(f, "tunable `{k}` given twice"),
            Self::Missing(k) => write!(f, "tunable `{k}` is missing"),
            Self::MissingUnit(k) => write!(f, "tunable `{k}` does not document its unit"),
            Self::BadValue(k) => write!(f, "tunable `{k}` is not a valid number"),
        }
    }
}

impl std::error::Error for PackageError {}

/// A range-checked integral rate as `u32`.
#[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)] // Checked: integral, 1 to 65535.
fn whole_hz(hz: f64) -> u32 {
    hz as u32
}

const MOTION_KEYS: [&str; 11] = [
    "run_speed",
    "walk_speed",
    "backward_scale",
    "ground_accel",
    "air_accel",
    "jump_speed",
    "gravity",
    "max_fall_speed",
    "max_step_up",
    "max_slope",
    "ground_snap",
];

impl Tunables {
    /// Reads `[tunables.server] tick_rate` and every `[tunables.motion]` key.
    ///
    /// # Errors
    /// [`PackageError`] for the first problem found.
    pub fn parse(manifest: &str) -> Result<Tunables, PackageError> {
        let mut table = "";
        let mut tick_rate: Option<f64> = None;
        let mut motion: [Option<f64>; 11] = [None; 11];
        for (index, raw) in manifest.lines().enumerate() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some(name) = line.strip_prefix('[').and_then(|l| l.strip_suffix(']')) {
                table = name.trim();
                continue;
            }
            if table != "tunables.server" && table != "tunables.motion" {
                continue;
            }
            let (assignment, unit) = line.split_once('#').ok_or_else(|| {
                PackageError::MissingUnit(line.split('=').next().unwrap_or("").trim().to_owned())
            })?;
            let (key, value) = assignment
                .split_once('=')
                .ok_or(PackageError::Syntax(index + 1))?;
            let (key, value) = (key.trim(), value.trim());
            if key.is_empty() || value.is_empty() {
                return Err(PackageError::Syntax(index + 1));
            }
            if unit.trim().is_empty() {
                return Err(PackageError::MissingUnit(key.to_owned()));
            }
            let number: f64 = value
                .parse()
                .map_err(|_| PackageError::BadValue(key.to_owned()))?;
            if !number.is_finite() {
                return Err(PackageError::BadValue(key.to_owned()));
            }
            let slot = match (table, key) {
                ("tunables.server", "tick_rate") => &mut tick_rate,
                ("tunables.server", _) => continue, // other server tunables are not the client's
                _ => {
                    let i = MOTION_KEYS
                        .iter()
                        .position(|k| *k == key)
                        .ok_or_else(|| PackageError::Unknown(key.to_owned()))?;
                    motion
                        .get_mut(i)
                        .ok_or_else(|| PackageError::Unknown(key.to_owned()))?
                }
            };
            if slot.replace(number).is_some() {
                return Err(PackageError::Duplicate(key.to_owned()));
            }
        }
        let hz = tick_rate.ok_or(PackageError::Missing("tick_rate"))?;
        let tick_rate = (hz.fract() == 0.0 && hz >= 1.0 && hz <= f64::from(u16::MAX))
            .then(|| TickRate::new(whole_hz(hz)))
            .flatten()
            .ok_or_else(|| PackageError::BadValue("tick_rate".to_owned()))?;
        let mut values = [0.0f32; 11];
        for ((v, m), key) in values.iter_mut().zip(motion).zip(MOTION_KEYS) {
            #[allow(clippy::cast_possible_truncation)] // Tunables are small decimals.
            let f = m.ok_or(PackageError::Missing(key))? as f32;
            *v = f;
        }
        let [
            run_speed,
            walk_speed,
            backward_scale,
            ground_accel,
            air_accel,
            jump_speed,
            gravity,
            max_fall_speed,
            max_step_up,
            max_slope,
            ground_snap,
        ] = values;
        Ok(Tunables {
            tick_rate,
            motion: MotionParams {
                run_speed,
                walk_speed,
                backward_scale,
                ground_accel,
                air_accel,
                jump_speed,
                gravity,
                max_fall_speed,
                max_step_up,
                max_slope,
                ground_snap,
            },
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    type TestResult = Result<(), Box<dyn std::error::Error>>;

    #[test]
    fn the_shipped_manifest_matches_the_engine_defaults() -> TestResult {
        // The server's tests hold the same equality, so a divergence fails on both sides
        // (prediction must run the server's exact parameters).
        let t = Tunables::parse(PACKAGE_TOML)?;
        assert_eq!(t.motion, MotionParams::DEFAULT);
        assert_eq!(t.tick_rate.hz(), 30);
        assert_ne!(content(), ContentHash::ZERO);
        Ok(())
    }

    #[test]
    fn malformed_manifests_are_refused() {
        let base = "[tunables.server]\ntick_rate = 30 # Hz\n[tunables.motion]\n";
        let with = |extra: &str| Tunables::parse(&format!("{base}{extra}")).err();
        assert_eq!(
            with("run_speed = 7.0\n"),
            Some(PackageError::MissingUnit("run_speed".to_owned()))
        );
        assert_eq!(
            with("speed = 7.0 # m/s\n"),
            Some(PackageError::Unknown("speed".to_owned()))
        );
        assert_eq!(
            with("run_speed = fast # m/s\n"),
            Some(PackageError::BadValue("run_speed".to_owned()))
        );
        assert_eq!(
            with("run_speed = 7 # m/s\nrun_speed = 7 # m/s\n"),
            Some(PackageError::Duplicate("run_speed".to_owned()))
        );
        assert_eq!(
            with("run_speed = 7.0 # m/s\n"),
            Some(PackageError::Missing("walk_speed"))
        );
        assert_eq!(
            Tunables::parse("[tunables.server]\ntick_rate = 0.5 # Hz\n").err(),
            Some(PackageError::BadValue("tick_rate".to_owned()))
        );
    }
}
